### PR TITLE
Capitalize P-s in WordPress

### PR DESCRIPTION
**Pull request by szepeviktor**
Hello @brianvarskonst!

Now it is not late to call this plugin another name, as it is not an Automattic product.
"... for WordPress" or similar

### CODE REVIEW

**Comment by szepeviktor** [comment]
Also going with a "vendor-name\project-name" style PHP namespace.
Something like `namespace BrianVarskonst\WordPress\NonceManager;`

**Comment by szepeviktor** [comment]
The first few commits are made with a non-GitHub email address: https://github.com/brianvarskonst/wordpress-nonce-oop/commits/master
(_more in this [Hexenküche](https://github.com/szepeviktor/small-project/blob/master/README.md)_)

**Review by brianvarskonst — APPROVED** [review]
Thank you for the contribution and work. 🙏🏻 

I still work on this refactoring so hopefully you invested not too much work into this, because there are many things changing and I had this also on my list. 😄

**Comment by brianvarskonst** [comment]
> Also going with a "vendor-name\project-name" style PHP namespace.
Something like namespace BrianVarskonst\WordPress\NonceManager;

You are totally right, this also on my list todo.

**Comment by brianvarskonst** [comment]
> The first few commits are made with a non-GitHub email address: https://github.com/brianvarskonst/wordpress-nonce-oop/commits/master (_more in this [Hexenküche](https://github.com/szepeviktor/small-project/blob/master/README.md)_)

Yeah, the reason is I changed my primary E-Mail Address, which every commit since the last 6 Months got lost also on my Github commit history. 😄

**Pull request merged**
